trigger:
  branches:
    include:
      - master

pool:
  name: onevfrontendVM

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: CmdLine@2
      displayName: "Install requirements"
      inputs:
        script: |
          #python3.11 -m venv antenv
          python3 --version
          pip3 --version
          echo "No venv created in CI"
          #source antenv/bin/activate
          #python -m pip install --upgrade pip
          #pip install -r backend/requirements.txt
        failOnStderr: true

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'backend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  jobs:
  - deployment: DeploymentJob
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: onevapiback'
            inputs:
              ConnectedServiceName: 5f235e97-d4b5-495d-ab4b-9142fe2b57d7
              appType: 'webAppLinux'
              appName: 'onevapiback'
              package: '$(Pipeline.Workspace)/drop/backend.zip'
              runtimeStack: 'PYTHON|3.11'
